version: '2'

services: 
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  project:
    image: bunnies:stable
    build: .
    tty: true
    volumes:
      - .:/opt/app
    depends_on:
      - redis
      