# Generated by Django 3.2.18 on 2023-04-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnies', '0002_rabbithole_bunnies_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbithole',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rabbithole',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
